name: 🚀 Feature Request
description: Suggest a new feature or enhancement for Plazen
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Your ideas help make Plazen better for everyone.

  - type: checkboxes
    id: existing-check
    attributes:
      label: Is there an existing feature request for this?
      description: Please search the existing issues to see if this feature has already been requested.
      options:
        - label: I have searched the existing issues and this feature has not been requested
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe what you're trying to accomplish.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: Describe how you envision this feature working...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered...
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of Plazen does this feature relate to?
      options:
        - Task Management
        - Scheduling / Auto-scheduling
        - Calendar Integration (Google Calendar, iCal)
        - User Interface / UX
        - Mobile Experience
        - Settings / Preferences
        - Authentication
        - Performance
        - API / Integrations
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a real-world scenario where this feature would be beneficial.
      placeholder: "As a user, I want to... so that I can..."
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, screenshots, or examples from other apps that demonstrate what you have in mind.
      placeholder: Drag and drop images here or paste links...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Are you willing to contribute?
      description: Would you be interested in implementing this feature yourself?
      options:
        - label: I would like to work on this feature
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
      placeholder: Any additional information...
    validations:
      required: false
